Started with html parser module

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -39,6 +39,7 @@ AC_ARG_ENABLE([iconv-support], AS_HELP_STRING(--enable-iconv-support,enable icon
 AC_ARG_ENABLE([ssl-legacy-reneg], AS_HELP_STRING(--enable-ssl-legacy-reneg, enable unsafe legacy renegotation only needed for openssl 0.9.8l))
 AC_ARG_ENABLE([lua-module], AS_HELP_STRING(--enable-lua-module,Add Lua support to httest))
 AC_ARG_ENABLE([js-module], AS_HELP_STRING(--enable-js-module,Add JavaScript support to httest))
+AC_ARG_ENABLE([html-module], AS_HELP_STRING(--enable-html-module,Add html support to httest))
 AC_ARG_WITH(apr,AS_HELP_STRING(--with-apr=PATH,path to apr-1-config script),
 	[if test ! -x $withval/apr-1-config; then AC_MSG_ERROR($withval/apr-1-config do not exist or is not executable); else APR_CONFIG="$withval/apr-1-config"; fi],
 	[APR_CONFIG="apr-1-config"])
@@ -63,6 +64,9 @@ AC_ARG_WITH(lua,AS_HELP_STRING(--with-lua=PATH,path to lua source dir),
 AC_ARG_WITH(spidermonkey,AS_HELP_STRING(--with-spidermonkey=PATH,path to js-config script),
 	[if test ! -x $withval/js-config; then AC_MSG_ERROR($withval/js-config do not exist or is not executable); else JS_CONFIG="$withval/js-config"; fi],
 	[JS_CONFIG="js-config"])
+AC_ARG_WITH(libxml2,AS_HELP_STRING(--with-libxml2=PATH,path to xml2-config script),
+	[if test ! -x $withval/xml2-config; then AC_MSG_ERROR($withval/xml2-config do not exist or is not executable); else XML2_CONFIG="$withval/xml2-config"; fi],
+	[XML2_CONFIG="xml2-config"])
 AC_ARG_WITH(ssl,AS_HELP_STRING(--with-ssl=PATH,path to openssl source),
 	[if test ! -d $withval; then AC_MSG_ERROR($withval is not a directory); else OPENSSL_LIB_PATH="-L${withval}"; OPENSSL_INCLUDES="-I${withval}/include"; fi],
 	[OPENSSL_LIB_PATH=""; OPENSSL_INCLUDES=""])
@@ -126,6 +130,17 @@ if test "$enable_js_module" = "yes"; then
   LIBS="$LIBS `$JS_CONFIG --libs` -lstdc++"
   HTTEST_MODULES="$HTTEST_MODULES js_module.${OBJEXT}"
   MODULES="$MODULES js "
+fi
+if test "$enable_html_module" = "yes"; then
+  XML2_VERSION=`$XML2_CONFIG --version`
+  if test ! "$?" = "0"; then
+    echo "libxml2 is missing"
+    exit -1
+  fi
+  CFLAGS="$CFLAGS `$XML2_CONFIG --cflags`"
+  LIBS="$LIBS `$XML2_CONFIG --libs`"
+  HTTEST_MODULES="$HTTEST_MODULES html_module.${OBJEXT}"
+  MODULES="$MODULES html "
 fi
 
 if test -f ./generate_modules_c.sh; then
